### ISSUE TITLE
Miniz vs libzip

### ISSUE THREAD

**Issue by n0iz** [gtreshchev/RuntimeArchiver#9]
Hi,
why do you use miniz instead of libzip? Are there any dis-/advantages?
Since the latter are already included in the engine as a third party lib?

I'am just curious because i got into troubles using another plugin (DirectExcel) that also uses miniz through the xlnt librarie so i had to rewire the third party lib to get both working.

**Comment by gtreshchev** [comment]
Hi, the main rationale behind choosing miniz, specifically including it by source code, rather than using libzip from the engine's module (which is included as a dynamic/shared library), is that libzip is only supported on Windows Win64, Mac (OS X), and Unix-based platforms (Linux, Ubuntu, CentOS, etc). Therefore, libzip won't work on Windows ARM/Win32, Android, iOS, consoles (PS4/5, Xbox, Switch), VR platforms (Quest, SteamVR, Magic Leap, etc) and other platforms. There're quite a significant number of devs who use this plugin on these platforms which are not supported by libzip in UE without extending that module, which is why it uses miniz.

If you have any specific issues that you faced while using this plugin, please let me know.

**Comment by n0iz** [comment]
Thats a good point, thanks.

Like I said, I've only had problems with this particular plugin “DirectExcel” which uses the xlnt sources and includes the miniz sources so there are naming conflicts. But i think the problem is in the DirectExcel plugin, it looks like miniz gets exposed through a public header.
